# Fastfile
default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore") # Use match to handle code signing
    build_app(scheme: "wepaClient") # Build the app
    upload_to_testflight # Upload to TestFlight
  end
end